# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://cdn.cocoapods.org/'


# project 'BazelDemo.xcodeproj'

plugin 'cocoapods-bazel', {
  rules: {
    'apple_framework' => { load: '//:framework.bzl', rule: 'apple_library' }.freeze,
    # 'ios_application' => { load: '@build_bazel_rules_ios//rules:app.bzl', rule: 'ios_application' }.freeze,
    # 'ios_unit_test' => { load: '@build_bazel_rules_ios//rules:test.bzl', rule: 'ios_unit_test' }.freeze
  }.freeze,
}


target 'BazelDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  # s4_sdk
  # pod 'Alamofire'
  # pod 'Firebase', '10.8.0'
  # pod 'FirebaseCrashlytics', '10.8.0'
  # pod 'FirebaseRemoteConfig', '10.8.0'
  # pod 'FirebasePerformance', '10.8.0'
  # pod 'FirebaseDynamicLinks', '10.8.0'
  # pod 'FirebaseSessions', '10.8.0'


  # Pods for BazelDemo

  # target 'BazelDemoTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'BazelDemoSources' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for BazelDemoSources

# end
